### ISSUE TITLE
"configs/tdw_simple_objs_100.json" is missing

### ISSUE THREAD

**Issue by xzyaoi** [samarth4149/task2sim#1]
Hi,

Thanks for this amazing work! I am trying to replicate the project. However, I noticed that there is a required file named "tdw_simple_objs_100.json" missing (https://github.com/samarth4149/task2sim/blob/0cc37a1cfdef65dba564ead5e0a9c7c1bce8d769/generator/generator.py#L133) and at the same time, the simple_objs parameter is by default set to True.

I am wondering if you have any plans in uploading this file as well? Or maybe I just missed this file somewhere?

Many thanks for your support in advance!

Best regards,
Xiaozhe

**Comment by samarth4149** [comment]
Hi, thanks for spotting this. I have added the missing file. 

By default `simple_objs` is set to `True` correct, which uses the subset of objects used for training Task2Sim (100 class subset in Tables 2 and 3 of the paper). Setting it to `False` means using all the objects (the 237 class set).
